export const GREETINGS: Record<string, string> = {
  US: 'Hi, how are you?',
  CA: 'Hello, how are you?',
  MX: 'Hola, ¿cómo estás?',
  BR: 'Oi, como você está?',
  AR: '¿Qué hacés, cómo andás?',
  CL: '¿Cómo estás?',
  CO: '¡Hola, ¿cómo estás?',
  PE: '¡Hola, ¿cómo estás?',
  EC: '¡Hola, ¿cómo estás?',
  VE: '¡Hola, ¿cómo estás?',
  GY: "Hello, how yuh doin'?",
  SR: 'Hoi, hoe gaat het met jou?',
  GF: 'Salut, ça va?',
}
